// Team members (names + roles) from the Audioworkshop About page org chart.
export const team = [
  { name: "Wahyu Tanuwidjaja", role: "Chief Executive Officer (CEO), PT. Audioworkshop" },
  { name: "Djuhaeni A.Md", role: "Chief Operational Officer (COO), PT. Audioworkshop" },
  { name: "Novia Hadi Putri, S.I.Kom", role: "Brand Director of Z3RO" },
  { name: "Rudy Parwana S.E", role: "Head HRD & GA" },
  { name: "Suci Ariyanti S.AP", role: "Adm HRD & Legal" },
  { name: "Fahrul S", role: "Marketing Manager Alpine" },
  { name: "Shendy S.I.Kom", role: "Head of Substance5" },
  { name: "Sofa Amaliyah", role: "Creative Design, Substance5" },
  { name: "Dwi Mardiyati S.I.Kom", role: "Admin Online, Substance5" },
  { name: "Dadan K S.I.Kom", role: "Videographer, Substance5" },
  { name: "Ilyasa A", role: "Creative PT. Audioworkshop" },
  { name: "Thefan Sandjaya", role: "Director PT. Ibu Budi Bestari" },
  { name: "Eko Putranto S.E", role: "Head of Soundandmachine.com" },
  { name: "Julfikri Ahmad Mursyid, BA", role: "Journalist, Soundandmachine.com" },
  { name: "M Abi Rafdi Liyusena", role: "Videografer, Soundandmachine.com" },
  { name: "Tio Dwi Pamungkas", role: "Videografer, Soundandmachine.com" },
  { name: "Ratna Dewi Astutik S.E, M.M", role: "Purchasing / Accounting" },
  { name: "Twin Devani Ramayu S.E", role: "Finance / Accounting" },
  { name: "Reni Andini S.E", role: "Warehouse / Tax" },
  { name: "Rusman", role: "Warehouse, PT. Audioworkshop" },
  { name: "Candra", role: "Warehouse, PT. Audioworkshop" },
  { name: "Anan", role: "Warehouse, PT. Audioworkshop" },
  { name: "Peter Petu Blangor", role: "Driver / Expeditions, PT. Audioworkshop" },
  { name: "Marsad", role: "Driver / Expeditions, PT. Audioworkshop" },
  { name: "Untung Suwitno", role: "Tekhnisi" },
];
